export const restaruntData = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "158511",
      name: "Shreenath Pavbhaji Pulao",
      uuid: "6bb24cba-b9f3-4a85-8b95-e78831a8ff55",
      city: "16",
      area: "Bajaj Nagar",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "tv0l4849ug4emnqxzjzv",
      cuisines: ["Fast Food", "Street Food", "Snacks", "Indian"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 0,
      minDeliveryTime: 0,
      maxDeliveryTime: 0,
      slaString: "",
      lastMileTravel: 0,
      price: 200,
      slugs: {
        restaurant: "shreenath-pavbhaji-pulao-cuisine-dharampeth",
        city: "nagpur",
      },
      cityState: "16",
      address:
        "Madhav Nagar,Near Lush House, Abhyankar Nagar,Nagpur, Maharashtra ",
      locality: "Dharampeth",
      parentId: 9227,
      unserviceable: true,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "50% off",
        shortDescriptionList: [
          {
            meta: "50% off | Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "50% OFF",
        shortDescriptionList: [
          {
            meta: "Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: false,
        nextOpenMessage: "Opens next at 1 pm, today",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      hasSurge: false,
      sla: {
        restaurantId: "158511",
        deliveryTime: 0,
        minDeliveryTime: 0,
        maxDeliveryTime: 0,
        lastMileTravel: 0,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE_WITH_BANNER",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.0",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "532078",
      name: "Foodies Squad Cafe",
      uuid: "57dd314b-98b7-45f5-bb83-9d15f1081b54",
      city: "16",
      area: "Ayodhya Nagar",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "j5zqrdkqj5ovogl0ff1i",
      cuisines: ["Italian-American", "Chinese", "Beverages"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 0,
      minDeliveryTime: 0,
      maxDeliveryTime: 0,
      slaString: "",
      lastMileTravel: 0,
      price: 250,
      slugs: {
        restaurant: "foodies-squad-cafe-and-restro-ayodhya-nagar-ayodhya-nagar",
        city: "nagpur",
      },
      cityState: "16",
      address:
        "DATTATRAYA NAGAR, NEW SUBHEDAR ROAD, OPP. MAHAKALKAR SABHAGRIHA, ZONE NO.- 5, HANUMAN NAGAR, NAGPUR URBAN- 440024",
      locality: "Opp Mahakalkar Sabhagriha",
      parentId: 320265,
      unserviceable: true,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "50% off",
        shortDescriptionList: [
          {
            meta: "50% off | Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "50% OFF",
        shortDescriptionList: [
          {
            meta: "Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: false,
        nextOpenMessage: "Opens next at 10 am, today",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      hasSurge: false,
      sla: {
        restaurantId: "532078",
        deliveryTime: 0,
        minDeliveryTime: 0,
        maxDeliveryTime: 0,
        lastMileTravel: 0,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE_WITH_BANNER",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.5",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "532060",
      name: "S S SOUTH INDIAN ADDA",
      uuid: "fd25a2bf-ed80-4ada-9fdc-bc4bfa8098ab",
      city: "16",
      area: "Dharampeth",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "epol9230pl8pcluc5vws",
      cuisines: ["Chinese", "Beverages", "Snacks"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 0,
      minDeliveryTime: 0,
      maxDeliveryTime: 0,
      slaString: "",
      lastMileTravel: 0,
      price: 200,
      slugs: {
        restaurant: "s-s-south-indian-adda-dharampeth-dharampeth",
        city: "nagpur",
      },
      cityState: "16",
      address:
        "7031 SHIWAJI CHOWK TAWAKKAL LAYOUT KATOL BY PASS WADI NAGPUR ZONE NO 2 DHARAMPETH NAGPUR URBAN NAGPUR 1 MAHARASHTRA",
      locality: "Shiwaji Chowk",
      parentId: 320278,
      unserviceable: true,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "50% off",
        shortDescriptionList: [
          {
            meta: "50% off | Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "50% OFF",
        shortDescriptionList: [
          {
            meta: "Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: false,
        nextOpenMessage: "Opens next at 8 am, today",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      hasSurge: false,
      sla: {
        restaurantId: "532060",
        deliveryTime: 0,
        minDeliveryTime: 0,
        maxDeliveryTime: 0,
        lastMileTravel: 0,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE_WITH_BANNER",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.5",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "470941",
      name: "Snacks island",
      uuid: "aff27ca1-a1c3-45e6-9202-b0b666db36d8",
      city: "16",
      area: "Wadi",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "zeenfbexzgtoipuziznj",
      cuisines: ["Fast Food", "Snacks", "Beverages"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 0,
      minDeliveryTime: 0,
      maxDeliveryTime: 0,
      slaString: "",
      lastMileTravel: 0,
      price: 250,
      slugs: {
        restaurant: "snacks-island-wadi-wadi",
        city: "nagpur",
      },
      cityState: "16",
      address:
        "Plot no 59, Lane no 1, Behind MS Services Garage, Gandhinagar, Nagpur 440010.",
      locality: "Gazal Kitchen",
      parentId: 272400,
      unserviceable: true,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "50% off",
        shortDescriptionList: [
          {
            meta: "50% off | Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "50% OFF",
        shortDescriptionList: [
          {
            meta: "Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: false,
        nextOpenMessage: "Opens next at 1 pm, today",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      hasSurge: false,
      sla: {
        restaurantId: "470941",
        deliveryTime: 0,
        minDeliveryTime: 0,
        maxDeliveryTime: 0,
        lastMileTravel: 0,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE_WITH_BANNER",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "527965",
      name: "MANNLAVA REATAURANT AND COFFE DAY SHOP",
      uuid: "836090a3-f937-4fb5-8c61-ca7a3200e4c1",
      city: "16",
      area: "Ayodhya Nagar",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "vrtayxzngb4eumqcyfji",
      cuisines: [
        "North Indian",
        "Indian",
        "Chinese",
        "Biryani",
        "Thalis",
        "Snacks",
      ],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 0,
      minDeliveryTime: 0,
      maxDeliveryTime: 20,
      slaString: "",
      lastMileTravel: 0,
      price: 200,
      slugs: {
        restaurant:
          "mannlava-reataurant-and-coffe-day-shop-ayodhya-nagar-ayodhya-nagar-3",
        city: "nagpur",
      },
      cityState: "16",
      address:
        "HOUSE NO 1488 NEAR MATA MANDIR UNTAKHANA ROAD MEDICAL CHOWK NAGPUR ZONE NO 5 HANUMANNAGAR NAGPUR URBAN NAGPUR 1 MAHARASHTRA 440024",
      locality: "Untakhana Road",
      parentId: 317982,
      unserviceable: true,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "50% off",
        shortDescriptionList: [
          {
            meta: "50% off | Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "50% OFF",
        shortDescriptionList: [
          {
            meta: "Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: false,
        nextOpenMessage: "Opens next at 11 am, today",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      hasSurge: false,
      sla: {
        restaurantId: "527965",
        deliveryTime: 0,
        minDeliveryTime: 0,
        maxDeliveryTime: 0,
        lastMileTravel: 0,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE_WITH_BANNER",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },

  {
    type: "restaurant",
    data: {
      type: "F",
      id: "532083",
      name: "Swast Mast Nasta Point",
      uuid: "6dba32f6-51d3-49f0-b72f-8f41c5545103",
      city: "16",
      area: "Manish Nagar",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "yi24ss3ptrggts9klxsx",
      cuisines: ["Snacks", "South Indian"],
      tags: [],
      costForTwo: 10000,
      costForTwoString: "₹100 FOR TWO",
      deliveryTime: 0,
      minDeliveryTime: 0,
      maxDeliveryTime: 0,
      slaString: "",
      lastMileTravel: 0,
      price: 300,
      slugs: {
        restaurant: "swast-mast-nasta-point-manish-nagar-manish-nagar",
        city: "nagpur",
      },
      cityState: "16",
      address:
        "Shop no - 6, Siddhi Vinay Appartment,  Beltarodi,, Nagpur Gramin, Nagpur  (Rural), Nagpur, Maharashtra - 441108",
      locality: "Manish Nagar",
      parentId: 320273,
      unserviceable: true,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "50% off",
        shortDescriptionList: [
          {
            meta: "50% off | Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "50% OFF",
        shortDescriptionList: [
          {
            meta: "Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: false,
        nextOpenMessage: "Opens next at 8 am, today",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      hasSurge: false,
      sla: {
        restaurantId: "532083",
        deliveryTime: 0,
        minDeliveryTime: 0,
        maxDeliveryTime: 0,
        lastMileTravel: 0,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE_WITH_BANNER",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "523123",
      name: "Mom's Maggy mania",
      uuid: "a5579faa-5ef4-4968-a916-a1d8369f75fd",
      city: "16",
      area: "Sitabuldi",
      totalRatingsString: "20+ ratings",
      cloudinaryImageId: "ky36vdfzrtvx1enxvo1o",
      cuisines: ["Snacks"],
      tags: [],
      costForTwo: 18000,
      costForTwoString: "₹180 FOR TWO",
      deliveryTime: 0,
      minDeliveryTime: 0,
      maxDeliveryTime: 0,
      slaString: "",
      lastMileTravel: 0,
      price: 150,
      slugs: {
        restaurant: "mom's-maggy-mania-sitabuldi-sitabuldi",
        city: "nagpur",
      },
      cityState: "16",
      address: "527, Sitabuldi, Nagpur, Maharashtra 440012, India",
      locality: "Abhyankar Road",
      parentId: 312094,
      unserviceable: true,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "50% off",
        shortDescriptionList: [
          {
            meta: "50% off | Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "50% OFF",
        shortDescriptionList: [
          {
            meta: "Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: false,
        nextOpenMessage: "Opens next at 7 am, today",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      hasSurge: false,
      sla: {
        restaurantId: "523123",
        deliveryTime: 0,
        minDeliveryTime: 0,
        maxDeliveryTime: 0,
        lastMileTravel: 0,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE_WITH_BANNER",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 20,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "5279653",
      name: "MANNLAVA REATAURANT AND COFFE DAY SHOP",
      uuid: "836090a3-f937-4fb5-8c61-ca7a3200e4c1",
      city: "16",
      area: "Ayodhya Nagar",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "vrtayxzngb4eumqcyfji",
      cuisines: [
        "North Indian",
        "Indian",
        "Chinese",
        "Biryani",
        "Thalis",
        "Snacks",
      ],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 0,
      minDeliveryTime: 0,
      maxDeliveryTime: 0,
      slaString: "",
      lastMileTravel: 0,
      price: 200,
      slugs: {
        restaurant:
          "mannlava-reataurant-and-coffe-day-shop-ayodhya-nagar-ayodhya-nagar-3",
        city: "nagpur",
      },
      cityState: "16",
      address:
        "HOUSE NO 1488 NEAR MATA MANDIR UNTAKHANA ROAD MEDICAL CHOWK NAGPUR ZONE NO 5 HANUMANNAGAR NAGPUR URBAN NAGPUR 1 MAHARASHTRA 440024",
      locality: "Untakhana Road",
      parentId: 317982,
      unserviceable: true,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "50% off",
        shortDescriptionList: [
          {
            meta: "50% off | Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "50% OFF",
        shortDescriptionList: [
          {
            meta: "Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "50% off up to ₹100 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: "",
        title: "",
        amount: "",
        icon: "",
      },
      availability: {
        opened: false,
        nextOpenMessage: "Opens next at 11 am, today",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      hasSurge: false,
      sla: {
        restaurantId: "527965",
        deliveryTime: 0,
        minDeliveryTime: 0,
        maxDeliveryTime: 0,
        lastMileTravel: 0,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE_WITH_BANNER",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
];
